version: 2
jobs:
  build:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
        key: my-app-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
        key: my-app-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
          - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI